"""
預設配置文件，用於HyperForensics++專案
"""

from yacs.config import CfgNode as CN

# 創建配置節點
_C = CN()

# GENERAL
_C.GENERAL = CN()
_C.GENERAL.SEED = 42

# CUDA
_C.CUDA = CN()
_C.CUDA.USE_CUDA = True
_C.CUDA.CUDA_NUM = [0]

# DATASET
_C.DATASET = CN()
_C.DATASET.ROOT = ""
_C.DATASET.Train_data = ""
_C.DATASET.Val_data = ""
_C.DATASET.NUM_CLASSES = 2

# MODEL
_C.MODEL = CN()
_C.MODEL.NAME = "HRNetV2"
_C.MODEL.C = 12
_C.MODEL.IN_CHANNELS = 172
_C.MODEL.USE_3D = True
_C.MODEL.USE_ATTENTION = False
_C.MODEL.PRETRAINED = False

# TRAIN
_C.TRAIN = CN()
_C.TRAIN.EPOCH_START = 0
_C.TRAIN.EPOCH_END = 300
_C.TRAIN.BATCH_SIZE = 16
_C.TRAIN.LEARNING_RATE = 0.0001
_C.TRAIN.WEIGHT_DECAY = 0.00005
_C.TRAIN.NUM_WORKERS = 8
_C.TRAIN.PIN_MEMORY = True
_C.TRAIN.LOG_PATH = "./logs/training_log"
_C.TRAIN.SAVE_WEIGHT_PATH = "./checkpoints"
_C.TRAIN.LOG_LOSS = 10
_C.TRAIN.LOG_IMAGE = 50
_C.TRAIN.SAVE_WEIGHT_STEP = 4
_C.TRAIN.CHECKPOINT = ""
_C.TRAIN.VAL_FREQ = 4
_C.TRAIN.BAND_REG = False

# TRAIN.LOSS
_C.TRAIN.LOSS = CN()
_C.TRAIN.LOSS.NAME = "CrossEntropyLoss"
_C.TRAIN.LOSS.WEIGHTS = [0.01, 0.99]

# TRAIN.OPTIMIZER
_C.TRAIN.OPTIMIZER = CN()
_C.TRAIN.OPTIMIZER.NAME = "AdamW"

# TRAIN.SCHEDULER
_C.TRAIN.SCHEDULER = CN()
_C.TRAIN.SCHEDULER.NAME = "MultiStepLR"
_C.TRAIN.SCHEDULER.MILESTONES = [200, 350, 450]
_C.TRAIN.SCHEDULER.GAMMA = 0.1

# TEST
_C.TEST = CN()
_C.TEST.BATCH_SIZE = 16
_C.TEST.NUM_WORKERS = 4
_C.TEST.RESULTS_NUM = 5
_C.TEST.RESULTS_PATH = "./logs/validation_results"

# 導出默認配置
CfgNode = CN

def get_cfg():
    """
    獲取默認配置副本。
    """
    return _C.clone() 