CUDA:
  USE_CUDA: True
  CUDA_NUM: [3]     # 使用 GPU 3

DATASET:
  ROOT: "/ssd8/HyperForensics_Data/HyperForensics_Dataset"  # 修改為資料集根目錄
  SPLIT_ROOT: "/ssd8/HyperForensics_Data/HyperForensics_Dataset/dataset_split_txt"  # 資料集分割檔案的根目錄
  CONFIGS:  # 資料集配置
    - name: "Origin"
      train: "Origin/train.txt"
      val: "Origin/val.txt"
      test: "Origin/test.txt"
    - name: "config1"
      train: "Config1/train.txt"
      val: "Config1/val.txt"
      test: "Config1/test.txt"
    - name: "config2"
      train: "Config2/train.txt"
      val: "Config2/val.txt"
      test: "Config2/test.txt"
    - name: "config3"
      train: "Config3/train.txt"
      val: "Config3/val.txt"
      test: "Config3/test.txt"
    - name: "config4"
      train: "Config4/train.txt"
      val: "Config4/val.txt"
      test: "Config4/test.txt"
  NUM_CLASSES: 2

MODEL:
  NAME: "HRNetV2"
  C: 12
  IN_CHANNELS: 172
  USE_3D: True
  USE_ATTENTION: False

TRAIN:
  EPOCH_START: 0
  EPOCH_END: 100
  BATCH_SIZE: 1  # 減少批次大小
  LEARNING_RATE: 0.0005
  NUM_WORKERS: 2  # 減少工作執行緒數量
  LOG_PATH: "/ssd1/dannyliu/HSI_Adv_Atk/HyperForensics++/logs/train_log" 
  SAVE_WEIGHT_PATH: "/ssd1/dannyliu/HSI_Adv_Atk/HyperForensics++/logs/weights"
  SAVE_INTERVAL: 5
  CHECKPOINT: ""

TEST:
  BATCH_SIZE: 1  # 減少批次大小
  NUM_WORKERS: 2  # 減少工作執行緒數量
  CHECKPOINT: ""
  RESULTS_PATH: "/ssd1/dannyliu/HSI_Adv_Atk/HyperForensics++/logs/test_result" 