CUDA:
  USE_CUDA: True
  CUDA_NUM: [3]     # 使用 GPU 3

DATASET:
  ROOT: "/ssd8/HyperForensics_Data/HyperForensics_Dataset"
  SPLIT_ROOT: "/ssd8/HyperForensics_Data/HyperForensics_Dataset/dataset_split_txt"
  NUM_CLASSES: 2
  CONFIGS:
    - name: "Origin"
      train: "Origin/train.txt"
      val: "Origin/val.txt"
      test: "Origin/test.txt"
    - name: "config1"
      train: "config1/train.txt"
      val: "config1/val.txt"
      test: "config1/test.txt"
  INFO_CSV: "/ssd8/HyperForensics_Data/HyperForensics_Dataset/info_csv.csv"

MODEL:
  NAME: "HRNetV2"
  C: 12
  IN_CHANNELS: 172
  USE_3D: True
  USE_ATTENTION: True
  INPUT_CHANNELS: 172
  OUTPUT_CHANNELS: 1
  PRETRAINED: false

TRAIN:
  EPOCH_START: 0
  EPOCH_END: 100
  BATCH_SIZE: 4
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  NUM_WORKERS: 1
  PIN_MEMORY: true
  LOG_PATH: "/ssd1/dannyliu/HSI_Adv_Atk/HyperForensics++/logs/training_log"
  SAVE_WEIGHT_PATH: "/ssd1/dannyliu/HSI_Adv_Atk/HyperForensics++/checkpoints"
  CHECKPOINT: ""  # 如果要從某個檢查點繼續訓練，填寫路徑
  SAVE_FREQ: 5  # 每多少個 epoch 保存一次
  VAL_FREQ: 1   # 每多少個 epoch 驗證一次
  LOSS:
    NAME: "CrossEntropyLoss"
    WEIGHTS: [1.0, 50.0]  # 大幅提高偽造樣本（類別1）的權重，因為偽造區域僅佔1-2%
  OPTIMIZER:
    NAME: "Adam"
    BETA1: 0.9
    BETA2: 0.999
  SCHEDULER:
    NAME: "ReduceLROnPlateau"
    MODE: "max"
    FACTOR: 0.1
    PATIENCE: 5
    VERBOSE: true

TEST:
  BATCH_SIZE: 4 
  NUM_WORKERS: 1  
  CHECKPOINT: ""
  RESULTS_PATH: "/ssd1/dannyliu/HSI_Adv_Atk/HyperForensics++/logs/test_result" 